### ISSUE TITLE
LYWSD02 device

### ISSUE THREAD

**Issue by zaikindenis** [save2love/mi-ble-mqtt#1]
Thanks for the sketch!!!!

Please add support for LYWSD02 device.

**Comment by zaikindenis** [comment]
here is the code supporting this device https://github.com/1technophile/OpenMQTTGateway/blob/development/ZgatewayBT.ino

**Comment by save2love** [comment]
Thank you for your interest in my project.
It will be a bit hard to check working with LYWSD02 without real device. Could you integrate necessary functionality with LYWSD02 in the project and do pull request?

**Comment by zaikindenis** [comment]
I can do simple programs. I tried to add support myself, but nothing happened. Apparently LYWSD02 has a different coding. here is another link (rus lang) to an interesting manual for LYWSD02 : https://habr.com/ru/post/452558/

**Comment by save2love** [comment]
Thank you, I have read this post earlier.
I'll try to write a test sketch for your LYWSD02 and you test it with your device. After that you send me a result log and I'll look what I can do next. I don't have much free time so I don't promise to do it quickly.  Deal?

**Comment by zaikindenis** [comment]
Ок

**Comment by zaikindenis** [comment]
Привет. Нет в планах поддержки LYWSD02 ?
Симпатичные датчики с часами. Может купить тебе ее ?

**Comment by save2love** [comment]
Я думал купить себе такой, но не было необходимости, т.к. LYWSDCGQ (BLE c LCD экраном) покрывают все что мне нужно. Спасибо за предложение. Если вы из Украины, то готов просто одолжить для реализации поддержки.

**Comment by zaikindenis** [comment]
Привет, я из России. готов заплатить за реализацию поддержки данных девайсов и за сам девайс, что бы тебе проще было тестировать.

**Comment by save2love** [comment]
Девайс заказал, так что когда он будет у меня, поддержка появится. Ничего не нужно, спасибо.

**Comment by save2love** [comment]
@zaikindenis Хорошие новости, я добавил поддержку LYWSD02 и не только. Пожалуйста проверьте у себя и сообщите о результатах;)
